name: CI

on: 
  pull_request:
    branches: [main, develop]
  push:
    branches: [main, develop]

jobs:
  Continuous_Integration:
    runs-on: ubuntu-latest
    
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Cache Poetry installation
        uses: actions/cache@v4
        with:
          path: ~/.local
          key: poetry-${{ runner.os }}-${{ hashFiles('**/poetry.lock') }}

      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: ~/.cache/pypoetry
          key: poetry-deps-${{ runner.os }}-${{ hashFiles('**/poetry.lock') }}

      - name: Install dependencies with Poetry
        run: |
          poetry config virtualenvs.create true
          poetry config virtualenvs.in-project true
          poetry install --no-root

      - name: Run linting (opcional)
        run: |
          poetry run ruff check .
          poetry run ruff format --check .
        continue-on-error: true

      - name: Run tests with taskipy
        run: poetry run task test

      - name: Upload coverage reports (opcional)
        uses: codecov/codecov-action@v4
        if: success()
        with:
          file: ./coverage.xml
          fail_ci_if_error: false